# Generated by Django 2.2.1 on 2019-05-21 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=15)),
                ('age', models.IntegerField(default=15)),
                ('date_birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDegree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_degree', models.IntegerField(default=15)),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='umapp.Student')),
            ],
        ),
    ]
